import type {Metadata} from 'next'
import {Rubik} from 'next/font/google'
import './globals.css'
import '../styles/Header.css'
import '../styles/AppLogo.css'
import StyledComponentsRegistry from '../../lib/registry'
const rubik = Rubik({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Our styling project',
  description: 'Generated by create next app',
  keywords: ['products', 'small applientces', 'appliances', 'beko'],
  // icons: {
  //   icon: ''
  // }
  verification: {
    google: '',
    other: {
      facebook: 'faceboookfsdfdsfdss',
    },
  },
  openGraph: {
    title: 'Our products  store',
    description: '',
    url: 'localhost:3000',
    siteName: 'Products | Store',
    images: [
      {
        alt: 'tes',
        url: '',
        width: '300',
        height: '300',
      },
    ],
    type: 'website',
    locale: 'en_EN',
  },
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
    },
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
